audit_header: false
title: East Valley Real Estate Video Blog with Katie Evans
description: Our mission at Keller Williams East Valley is to be your best resource for East Valley real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Keller Williams East Valley, your professional East Valley Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Katie Evans
  title:
  license_number:
  about_markdown: |
    I joined the Keller Williams East Valley market center in early 2012. I grew up in Mesa, Arizona, where I attended Mountain View High School and graduated in 1993. Later, I attended, and graduated from, Brigham Young University with a B.S. in 1998. I returned to Arizona with my husband, Jason, and daughter, Katelyn, in 1999. Jason and I started a successful custom home electronics business called Components Electronics System, LLC, which we owned and operated for 10 years and sold at the end of 2013. Working in high-end custom and luxury homes with Components solidified my desire to work with home sellers and buyers in the dynamic Arizona real estate market. I specialize in the East Valley cities Mesa, Gilbert, Chandler, Tempe, Queen Creek, and Apache Junction.
  market: East Valley
  brand: Keller Williams East Valley
  brokerage:
  address: '2077 E. Warner Rd., Ste.<BR>#110, Tempe, AZ 85284'
  phone: 480-415-1341
  phone_type:
  phone2:
  phone2_type:
  email: Katie@Living48re.com
  url: http://www.Living48re.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.living48re.com/home_value
  second_CTA_text: Home Search
  second_CTA_URL: https://www.living48re.com/search#?q_limit=36&q_prioritize=agents.0.id=ke085|office.id=kwevt01&mlsId=21&status=1|3&q_sort=createdAt-&q_offset=0

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your East Valley Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.living48re.com/home_value

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a East Valley Home?"
    CTA_text2: "Search the entire MLS for your East Valley home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.living48re.com/search#?q_limit=36&q_prioritize=agents.0.id=ke085|office.id=kwevt01&mlsId=21&status=1|3&q_sort=createdAt-&q_offset=0

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/Living48RealEstateTeam/
  linkedin_url: https://www.linkedin.com/in/KatieBEvans
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UC_hZWu-x91-2NSqIpn6he0g?view_as=subscriber
  twitter_url: https://twitter.com/living48re
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Katie-Evans-Living48/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'East Valley Real Estate Podcast with Katie Evans'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the East Valley Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Keller Williams East Valley - your professional East Valley Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in East Valley, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Katie Evans'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Living 48 Real Estate Journal
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
  accent_color: '#61d4dd'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
